### PR TITLE
Automatic version numbers

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
This PR uses [setuptools-scm](https://github.com/pypa/setuptools_scm/) to automatically track the software version number, based on the git tags created whenever a new release is made.

This makes things simpler (because it's automated) and easier (because you get more information in the version strings).

Advantages:
* A simpler and less error prone release process. No one has to update the version string manually before creating a new release! This is easy to forget by accident. Instead setuptools-scm automatically handles it all.
* Easier tracking of development versions. This is a big win. Before, if someone installed a development version of the code, made changes, and installed the modified version, then there would be no difference in the version number compared to the official release. Now using setuptools-scm, the version number keeps track of these changes, so you'll see `dev` on the end of the version number (plus the last commit hash & other details).

What does this look like?
* For official releases, the version numbers will look exactly the same, eg: `0.2.0`.
* Developers using the main branch or a new feature, will see version numbers that look like this `0.0.3.dev3+gb951592`. There's a "dev" and the latest git hash is also incluced, making it super easy to figure out which commit was checked out. It can even keep track of a dirty, uncommitted state (you'll see a "d" then a number, eg: `0.0.3.dev3+gb951592.d20220901`)

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
GG and I have been occasionally having trouble keeping track of exactly which commit we have installed and are using, especially while we trial the new microexpansion joint feature. So the need for better automatic version numbering is a result of those discussions.

**Comment by GenevieveBuckley** [comment]
It turns out we need to switch over from the old setup.py format to the newer setup.cfg for the CI builds to run. I've done that now, so hopefully that should fix the issue.

**Comment by GenevieveBuckley** [comment]
> This PR uses [setuptools-scm](https://github.com/pypa/setuptools_scm/) to automatically track the software version number, based on the git tags created whenever a new release is made.
> 
> This makes things simpler (because it's automated) and easier (because you get more information in the version strings).
> 
> Advantages:
> 
>     * A simpler and less error prone release process. No one has to update the version string manually before creating a new release! This is easy to forget by accident. Instead setuptools-scm automatically handles it all.
> 
>     * Easier tracking of development versions. This is a big win. Before, if someone installed a development version of the code, made changes, and installed the modified version, then there would be no difference in the version number compared to the official release. Now using setuptools-scm, the version number keeps track of these changes, so you'll see `dev` on the end of the version number (plus the last commit hash & other details).
> 
> 
> What does this look like?
> 
>     * For official releases, the version numbers will look exactly the same, eg: `0.2.0`.
> 
>     * Developers using the main branch or a new feature, will see version numbers that look like this `0.0.3.dev3+gb951592`. There's a "dev" and the latest git hash is also incluced, making it super easy to figure out which commit was checked out. It can even keep track of a dirty, uncommitted state (you'll see a "d" then a number, eg: `0.0.3.dev3+gb951592.d20220901`)

**Comment by patrickcleeve2** [comment]
Good change, thanks @GenevieveBuckley.

Approved and merged

**Pull request merged**
