### PR TITLE
Make turning off the ion beam at the end optional

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
The user I work most closely with is unhappy that a recent change here is now turning off the ion beam after every run. Since that wasn't the behaviour before, I think the change could be made optional.

This PR makes the ion beam turn off only when the user has added `imaging: # Ion beam imaging parameters: true` to the `imaging` section of the protocol file, eg:
```yaml
imaging: # Ion beam imaging parameters
    turn_ion_beam_off_afterwards: true  # turns off ion beam after program is finished
```

@MoritzWM, would adding a line like this to your protocol file work for you?

### CODE REVIEW

**Comment by MoritzWM** [comment]
Sure go ahead!

**Comment by patrickcleeve2** [comment]
Is there a particular reason this was added @MoritzWM? 

In our experience, the user would want to manually image afterwards and want the beam on, or not be present so the beam would auto-shutoff after about an hour which would cover that case.

 Could we just remove this line instead? Happy to support either, but what is your experience @GenevieveBuckley?

**Comment by MoritzWM** [comment]
Hi!
On our machine, the beam isn't turned off after milling, so to save our apertures we implemented this. I discussed with Genevieve that probably the best would be for the script to ask the user whether he/she wants the beam to turn off in the end

**Comment by patrickcleeve2** [comment]
Ok, that makes sense to me. @GenevieveBuckley if you change this to ask_user instead of a config flag, I will merge it. Thanks

**Pull request merged**
